spring.config.import=optional:application-secret.properties

spring.application.name=CivicPulseAi


# Neon PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-patient-rain-aow6jvyz-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}